---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: "example-docker-strategy"
    name: "example-docker-strategy"
  spec: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: "example-docker-strategy"
    name: "example-docker-strategy"
  spec:
    output:
      to:
        kind: "ImageStreamTag"
        name: "example-docker-strategy:latest"
    resources: {}
    source:
      git:
        ref: "master"
        uri: "https://github.com/sdirbach/openshift-examples.git"
      contextDir: "BuildConfig/dockerStrategy"
      type: Git
    strategy:
      dockerStrategy:
      type: Docker
