---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: "example-local-pipeline-strategy"
    name: "example-local-pipeline-strategy"
  spec: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: "example-local-pipeline-strategy"
    name: "example-local-pipeline-strategy"
  spec:
    output:
      to:
        kind: "ImageStreamTag"
        name: "example-local-pipeline-strategy:latest"
    resources: {}
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfile: |-
          node('master') {
            stage('build') {
              echo 'Building...'
              openshiftBuild(buildConfig: 'example-docker-strategy', showBuildLogs: 'true')
            }
            stage('test') {
              echo 'Testing...'
            }
            stage('deploy') {
              echo 'Deploying...'
            }
          }
