---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    build: "example-local-pipeline-strategy"
  name: "example-local-pipeline-strategy"
spec: {}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: "example-local-pipeline-strategy"
  name: "example-local-pipeline-strategy"
spec:
  output:
    to:
      kind: "ImageStreamTag"
      name: "example-local-pipeline-strategy:latest"
  resources: {}
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node('master') {
          stage('build') {
            echo 'Building...'
            sh "oc start-build example-docker-strategy -F"
          }
          stage('test') {
            echo 'Testing...'
          }
          stage('deploy') {
            echo 'Deploying...'
          }
        }
