---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    build: "example-git-pipeline-strategy"
  name: "example-git-pipeline-strategy"
spec: {}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: "example-git-pipeline-strategy"
  name: "example-git-pipeline-strategy"
spec:
  output:
    to:
      kind: "ImageStreamTag"
      name: "example-git-pipeline-strategy:latest"
  resources: {}
  source:
    git:
      ref: "master"
      uri: "https://github.com/sdirbach/openshift-examples.git"
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: "BuildConfig/jenkinsPipelineStrategy/Jenkinsfile"
