node('master') {
  stage('build') {
    echo 'Building...'
    sh "oc start-build example-docker-strategy -F"
  }
  stage('test') {
    echo 'Testing...'
  }
  stage('deploy') {
    echo 'Deploying...'
  }
}
